[package]
name = "tasks-paralle-execute"
version = "0.1.0"
authors = ["Yangsibai <yangsibai@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.0"
crossbeam = "0.7"
